<template><div><h1 id="css-技巧" tabindex="-1"><a class="header-anchor" href="#css-技巧"><span>CSS 技巧</span></a></h1>
<h2 id="透明图片实现阴影" tabindex="-1"><a class="header-anchor" href="#透明图片实现阴影"><span>透明图片实现阴影</span></a></h2>
<div class="language-css line-numbers-mode" data-highlighter="shiki" data-ext="css" data-title="css" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">filter</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">: drop-shadow(0 0 10px rgba(0</span><span style="--shiki-light:#A626A4;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> 0</span><span style="--shiki-light:#A626A4;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> 0</span><span style="--shiki-light:#A626A4;--shiki-dark:#ABB2BF">,</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD"> 0</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">.5</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">));</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>使用filter属性就可以实现，不过这个属性不支持多重阴影。</p>
<h2 id="将图标转换颜色" tabindex="-1"><a class="header-anchor" href="#将图标转换颜色"><span>将图标转换颜色</span></a></h2>
<div class="language-css line-numbers-mode" data-highlighter="shiki" data-ext="css" data-title="css" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">filter</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">: brightness(0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">invert(14%</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">sepia(100%</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">saturate(7472%</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">hue-rotate(345deg</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">brightness(102%</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">) </span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">contrast(104%</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">);</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>同样可以使用filter属性实现，需要注意的是如果的原图片不是纯黑色的直接进行转换会出现色差，使用<code v-pre>brightness(0)</code>先将图片转换为黑色；还有需要注意的就是如果原图有复杂图案这个就不起作用了，只适用于图标；</p>
</div></template>


